title: its-seon
description: Hi i'm student and i'm studying ROBOTICS
author: Juno Seon
avatar: /logo.png
email: its.seon99@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
#
# google_analytics:

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
#
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ngzhio
  card: summary
logo: logo.png
social:
  name: Juno Seon
  links:
    - https://github.com/its-seon
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
